{% set name = "docarray" %}
{% set version = "0.40.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/docarray-{{ version }}.tar.gz
  sha256: c3f3b88b7b6128c10308dddbd21650c9845e270da850cf6718cb1d3d867d5986

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - poetry-core
  run:
    - python >=3.8
    - numpy >=1.17.3
    - orjson >=3.8.2
    - pydantic >=1.10.8
    - rich >=13.1.0
    - types-requests >=2.28.11.6
    - typing_inspect >=0.8.0

test:
  imports:
    - docarray
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/docarray/docarray
  summary: The data structure for unstructured data
  dev_url: https://github.com/docarray/docarray/
  license: Apache-2.0
  license_file: LICENSE
  description: |
    DocArray is a library for nested, unstructured data such as text, image, 
    audio, video, 3D mesh. It allows deep learning engineers to efficiently 
    process, embed, search, recommend, store, transfer the data with Pythonic 
    API.

    🌌 **All data types**: super-expressive data structure for representing 
    complicated/mixed/nested text, image, video, audio, 3D mesh data.

    🐍 **Pythonic experience**: designed to be as easy as Python list. If 
    you know how to Python, you know how to DocArray. Intuitive idioms and 
    type annotation simplify the code you write.

    🧑‍🔬 **Data science powerhouse**: greatly accelerate data scientists work 
    on embedding, matching, visualizing, evaluating via 
    Torch/Tensorflow/ONNX/PaddlePaddle on CPU/GPU.

    🚡 **Portable**: ready-to-wire at anytime with efficient and compact 
    serialization from/to Protobuf, bytes, JSON, CSV, dataframe.

    PyPI: [https://pypi.org/project/docarray](https://pypi.org/project/docarray)

  doc_url: https://docs.docarray.org/

extra:
  recipe-maintainers:
    - sugatoray
    - basnijholt
    # Maintainers from package (upstream) repository
    - hanxiao
    - nan-wang
    - JoanFM
